window:
  dynamic_title: true
  # dimensions:
  #   columns: 0
  #   lines: 0

  position:
    x: 2500
    y: 200

  padding:
    x: 5
    y: 0

  dynamic_padding: true
  # decorations: none

scrolling:
  history: 50000
  multiplier: 3

font:
  normal:
    family: Fira Code
    style: Regular

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Bold Italic

  size: 12.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  # use_thin_strokes: true

# draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#1d2021'
    foreground: '#d6d6d6'

    dim_foreground:    '#dbdbdb'
    bright_foreground: '#d9d9d9'
    dim_background:    '#202020'
    bright_background: '#3a3a3a'

background_opacity: 1
