# shell:
#   program: "wsl ~ -u kdi"

window:
  dimensions:
    columns: 120
    lines: 30

  dynamic_title: true

  # position:
  #   x: 1000
  #   y: 200

  # dynamic_padding: true
  padding:
    x: 8
    y: 8

  # decorations: none
  # opacity: 0.95

scrolling:
  history: 50000
  multiplier: 3

font:
  size: 13.0

  normal:
    family: Roboto Mono
    style: Regular

  bold:
    family: Roboto Mono
    style: Italic

  italic:
    family: Roboto Mono
    style: Thin

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  # use_thin_strokes: true

draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: F11, action: ToggleFullscreen }

colors:
  primary:
    background: "#212121"
    foreground: "#fafafa"

  # material 300
  normal:
    black:   '#000000'
    white:   '#fafafa'
    red:     '#E57373'
    green:   '#81C784'
    yellow:  '#FFD54F'
    blue:    '#64B5F6'
    magenta: '#CE93D8'
    cyan:    '#4DD0E1'
  bright:
    black:   '#757575'
    white:   '#fafafa'
    red:     '#E57373'
    green:   '#AED581'
    yellow:  '#FFE082'
    blue:    '#90CAF9'
    magenta: '#CE93D8'
    cyan:    '#4DD0E1'
