[window]
dimensions = { columns = 110, lines = 30 }
position = { x = 0, y = 0}
padding = { x = 4, y = 4 }
dynamic_padding = true
resize_increments = true
# decorations = "None"

[font]
size = 11
normal = { family = "Roboto Mono", style = "Regular" }
bold = { family = "Roboto Mono", style = "Bold" }
italic = { family = "Roboto Mono", style = "Regular Italic" }
bold_italic = { family = "Roboto Mono", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "N", mods = "Control | Shift", action = "SpawnNewInstance" },
]
