window:
  dynamic_title: true
  # dimensions:
  #   columns: 0
  #   lines: 0

  position:
    x: 1000
    y: 200

  padding:
    x: 5
    y: 8

  # dynamic_padding: true
  # decorations: none
  # opacity: 1

scrolling:
  history: 50000
  multiplier: 3

font:
  normal:
    family: Roboto Mono
    style: Regular

  bold:
    family: Roboto Mono
    style: Italic

  italic:
    family: Roboto Mono
    style: Thin

  size: 12.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  # use_thin_strokes: true

# draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#1E1E1E'
    foreground: '#D4D4D4'

  cursor:
    text: '#d4d4d4'
    cursor: '#d4d4d4'

  normal:
    black:   '#1e1e1e'
    red:     '#f44747'
    green:   '#608b4e'
    yellow:  '#dcdcaa'
    blue:    '#569cd6'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#d4d4d4'

  bright:
    black:   '#545454'
    red:     '#f44747'
    green:   '#608b4e'
    yellow:  '#dcdcaa'
    blue:    '#569cd6'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#d4d4d4'

key_bindings:
  - { key: F11, action: ToggleFullscreen }
