# shell:
#   program: "wsl ~ -u kdi"

window:
  dimensions:
    columns: 120
    lines: 30

  dynamic_title: true

  # position:
  #   x: 1000
  #   y: 200

  # dynamic_padding: true
  padding:
    x: 8
    y: 8

  # decorations: none
  # opacity: 0.95

scrolling:
  history: 50000
  multiplier: 3

font:
  size: 13.0

  normal:
    family: Roboto Mono
    style: Regular

  bold:
    family: Roboto Mono
    style: Italic

  italic:
    family: Roboto Mono
    style: Thin

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  # use_thin_strokes: true

draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: F11, action: ToggleFullscreen }
