window:
  dimensions:
    columns: 100
    lines: 35

  dynamic_title: true

  position:
    x: 1000
    y: 200

  # dynamic_padding: true
  padding:
    x: 8
    y: 8

  # decorations: buttonless
  # opacity: 0.95

scrolling:
  history: 50000
  multiplier: 3

font:
  normal:
    family: Roboto Mono
    style: Regular

  bold:
    family: Roboto Mono
    style: Italic

  italic:
    family: Roboto Mono
    style: Thin

  size: 11.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  # use_thin_strokes: true

# draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#1c1c1c'
    foreground: '#D4D4D4'

key_bindings:
  - { key: F11, action: ToggleFullscreen }
