"ui.menu" = { fg = "white", bg = "black" }
"ui.text.focus" = { modifiers = ["reversed"] }
"ui.menu.selected" = { modifiers = ["reversed"]}
"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "white",  modifiers = ["bold"] }
"ui.popup" = { bg = "black" }
"ui.window" = { fg = "gray" }
"ui.selection" = { modifiers = ["reversed"] }
"ui.statusline" = { fg = "white" }
"ui.statusline.inactive" = { fg = "gray" }
"ui.cursor" = { fg="gray",modifiers = ["reversed"] }

"attribute" = "light-yellow"
"type" = "light-blue"
"type.builtin" = { fg = "light-blue", modifiers = [ "italic" ] }
"constructor" = "light-yellow"
"constant" = "light-green"
"constant.builtin" = { fg = "light-green", modifiers = [ "italic" ] }
"string" = "light-green"
"comment" = "gray"
"variable" = "white"
"variable.builtin" = { fg = "light-red", modifiers = [ "italic" ] }
"label" = "light-magenta"
"punctuation" = "light-gray"
"keyword" = "light-red"
"operator" = "light-gray"
"function" = "light-yellow"
"function.builtin" = { fg = "light-yellow", modifiers = [ "italic" ] }
"tag" = "light-magenta"
"tag.builtin" = { fg = "light-magenta", modifiers = [ "italic" ] }
"namespace" = "light-gray"
"special" = "light-cyan"

"markup.heading" = "light-blue"
"markup.list" = "light-gray"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "light-blue" }
"markup.link.text" = "light-gray"
"markup.quote" = { fg = "light-gray", modifiers = ["italic"] }
"markup.raw" = { fg = "light-gray" }

"diff.plus" = "green"
"diff.delta" = "blue"
"diff.minus" = "red"

"debug" = "gray"
"info" = "blue"
"hint" = "cyan"
"warning" = "yellow"
"error" = "red"

"diagnostic" = { underline = { color = "gray", style = "curl" }}
"diagnostic.info" = { underline = { color = "blue", style = "curl" }}
"diagnostic.unnecessary" = { underline = { color = "cyan", style = "curl" }}
"diagnostic.hint" = { underline = { color = "cyan", style = "curl" }}
"diagnostic.deprecated" = { underline = { color = "yellow", style = "curl" }}
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" }}
"diagnostic.error" = { underline = { color = "red", style = "curl" }}
